# BTC Reproducible Multimodal Pipeline
Walk-forward CV + purged untouched final test. Start with validation, then baselines, then deep models.

## Deep model v2
This version uses a true VAE reconstruction objective, sinusoidal positional encoding before Transformer attention, and contiguous 48-hour validation/test sequences that include purge rows only as feature context. The final deep model is selected by walk-forward CV and evaluated once on the untouched holdout.

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
!pip install -q pandas numpy pyarrow scikit-learn joblib pyyaml torch

In [12]:
%cd "/content/drive/MyDrive/BTC reproducible multimodal pipeline"
!python run_pipeline.py --config config/btc_1h.yaml --stage validate

/content/drive/MyDrive/BTC reproducible multimodal pipeline

Dataset ready
  rows: 8759
  date: 2025-09-05 00:00:00+00:00 -> 2026-09-04 22:00:00+00:00
  market features: 27
  sentiment features: 10
  dev: 7444 | final purge gap: 1 | final test: 1314
  walk-forward folds: 5

In [13]:
import json, pandas as pd
out = "/content/drive/MyDrive/BTC reproducible multimodal pipeline/outputs/BTC_1h_target1h_sentiment_v4_ablation_200ep"
print(json.load(open(f"{out}/validation_report.json")))
print(json.load(open(f"{out}/split_manifest.json")))
df = pd.read_parquet(f"{out}/aligned_btc_market_sentiment.parquet")
print(df.shape, df.timestamp.min(), "->", df.timestamp.max())
display(df.head())

{'rows_before_dropna': 8783, 'first_timestamp': '2025-09-04 00:00:00+00:00', 'last_timestamp': '2026-09-04 22:00:00+00:00', 'duplicate_timestamps': 0, 'infinite_values': 0, 'missing_by_column': {'sentiment_score_lag_1h': 1, 'sentiment_score_lag_6h': 6, 'sentiment_score_lag_24h': 24}, 'target_distribution': {'1': 4395, '0': 4388}}
{'development_start': '2025-09-05 00:00:00+00:00', 'development_end': '2026-07-12 03:00:00+00:00', 'final_test_start': '2026-07-12 05:00:00+00:00', 'final_test_end': '2026-09-04 22:00:00+00:00', 'walk_forward_gap_hours': 1, 'final_test_gap_hours': 1, 'final_test_gap_start': '2026-07-12 04:00:00+00:00', 'final_test_gap_end': '2026-07-12 04:00:00+00:00', 'final_test_gap_rows': 1, 'folds': [{'fold': 1, 'train_start': '2025-09-05 00:00:00+00:00', 'train_end': '2025-10-26 18:00:00+00:00', 'validation_start': '2025-10-26 20:00:00+00:00', 'validation_end': '2025-12-17 11:00:00+00:00', 'train_rows': 1243, 'validation_rows': 1240}, {'fold': 2, 'train_start': '2025-09-05 00:00:00+00:00', 'train_end': '2025-12-17 10:00:00+00:00', 'validation_start': '2025-12-17 12:00:00+00:00', 'validation_end': '2026-02-07 03:00:00+00:00', 'train_rows': 2483, 'validation_rows': 1240}, {'fold': 3, 'train_start': '2025-09-05 00:00:00+00:00', 'train_end': '2026-02-07 02:00:00+00:00', 'validation_start': '2026-02-07 04:00:00+00:00', 'validation_end': '2026-03-30 19:00:00+00:00', 'train_rows': 3723, 'validation_rows': 1240}, {'fold': 4, 'train_start': '2025-09-05 00:00:00+00:00', 'train_end': '2026-03-30 18:00:00+00:00', 'validation_start': '2026-03-30 20:00:00+00:00', 'validation_end': '2026-05-21 11:00:00+00:00', 'train_rows': 4963, 'validation_rows': 1240}, {'fold': 5, 'train_start': '2025-09-05 00:00:00+00:00', 'train_end': '2026-05-21 10:00:00+00:00', 'validation_start': '2026-05-21 12:00:00+00:00', 'validation_end': '2026-07-12 03:00:00+00:00', 'train_rows': 6203, 'validation_rows': 1240}]}
(8759, 86) 2025-09-05 00:00:00+00:00 -> 2026-09-04 22:00:00+00:00

,timestamp,close_timestamp,asset,symbol,open,high,low,close,volume,quote_volume,...,sentiment_score,sentiment_label,positive_share,negative_share,neutral_share,has_news,coverage_available,sentiment_score_lag_1h,sentiment_score_lag_6h,sentiment_score_lag_24h
0,2025-09-05 00:00:00+00:00,2025-09-05 00:59:59.999000+00:00,BTC,BTCUSDT,110730.87,110929.30,110435.75,110451.62,457.22173,5.059984e+07,...,0.000000,None,0.0,0.0,0.0,0,1,-0.676787,-0.050987,0.000000
1,2025-09-05 01:00:00+00:00,2025-09-05 01:59:59.999000+00:00,BTC,BTCUSDT,110451.63,111136.00,110451.63,111121.51,336.74632,3.731146e+07,...,0.000000,None,0.0,0.0,0.0,0,1,0.000000,-0.377987,0.605158
2,2025-09-05 02:00:00+00:00,2025-09-05 02:59:59.999000+00:00,BTC,BTCUSDT,111121.51,111482.09,111040.79,111340.65,606.85268,6.754967e+07,...,0.743411,positive,1.0,0.0,0.0,1,1,0.000000,0.663947,0.476203
3,2025-09-05 03:00:00+00:00,2025-09-05 03:59:59.999000+00:00,BTC,BTCUSDT,111340.64,111340.65,111096.67,111311.77,264.75507,2.944260e+07,...,-0.385124,negative,0.0,1.0,0.0,1,1,0.743411,-0.145867,0.322667
4,2025-09-05 04:00:00+00:00,2025-09-05 04:59:59.999000+00:00,BTC,BTCUSDT,111311.78,111468.20,111144.51,111445.00,785.66095,8.749268e+07,...,0.000000,None,0.0,0.0,0.0,0,1,-0.385124,0.000000,-0.001300

## Baselines
Run after validation looks correct.

In [14]:
!python run_horizon_suite.py --stage baselines --horizons 1 6 24

Dataset ready
  rows: 8759
  date: 2025-09-05 00:00:00+00:00 -> 2026-09-04 22:00:00+00:00
  market features: 27
  sentiment features: 10
  dev: 7444 | final purge gap: 1 | final test: 1314
  walk-forward folds: 5

Best baseline by CV: hist_gradient_boosting market_only
Final holdout metrics: {'accuracy': 0.5228310502283106, 'precision': 0.5413223140495868, 'recall': 0.39280359820089955, 'f1': 0.45525629887054736, 'pr_auc': 0.540306640321264, 'mcc': 0.05149297652453508, 'roc_auc': 0.5293906369844444}

In [15]:
!python run_horizon_suite.py --stage deep --horizons 1 6 24

Dataset ready
  rows: 8759
  date: 2025-09-05 00:00:00+00:00 -> 2026-09-04 22:00:00+00:00
  market features: 27
  sentiment features: 10
  dev: 7444 | final purge gap: 1 | final test: 1314
  walk-forward folds: 5

Best baseline by CV: hist_gradient_boosting market_only
Final holdout metrics: {'accuracy': 0.5228310502283106, 'precision': 0.5413223140495868, 'recall': 0.39280359820089955, 'f1': 0.45525629887054736, 'pr_auc': 0.540306640321264, 'mcc': 0.05149297652453508, 'roc_auc': 0.5293906369844444}
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3198738  -0.423429   -0.2846517  ... -0.29023338 -0.50793851
 -0.5217816 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24042309 -0.63902956 -0.7304933  -0.5422848  -0.54142205 -0.66340856
 -0.67625165 -0.56582066 -0.62883352 -0.61569631 -0.40206959 -0.54155277
 -0.43151394 -0.33740969 -0.64680731 -0.47478176 -0.43574922 -0.62484007
 -0.56361152 -0.57648729 -0.74625795 -0.62244792 -0.68539541 -0.71182669
 -0.69904242 -0.69744766 -0.65938243 -0.39129839 -0.533226   -0.52104304
 -0.65925171 -0.72436913 -0.67052618 -0.71612733 -0.7023496  -0.6529903
  0.34538534 -0.34539659  0.42209096  0.51656122  0.33035272 -0.05326034
 -0.31923328 -0.29023338 -0.50793851 -0.5217816  -0.65023214]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.62576817 -0.19995918  1.32780679 ... -0.18073702  0.41114329
  0.05505301]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57782405 -0.67855544 -0.54356241 ... -0.31359808 -0.44248135
  0.13325916]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.18086204  2.43514675  4.8939678   2.95404944  2.30781476  1.9912077
  1.63560888  1.22658631  0.43013827 -0.23735019 -0.18072853  0.03779831
  0.39306017 -0.0185627   0.12479706 -0.02592491 -0.24317385 -0.55042237
  0.03051238 -0.23189529 -0.43590114  0.35861416  0.01498688  0.21936148
  2.01724248  3.45373915  3.1495614   2.26415644  0.97414751  0.65822073
  0.283339    0.05419481 -0.58641966 -0.53749081 -0.60229484 -0.38790051
 -0.36229805 -0.19437215 -0.64794947 -0.32235899  0.06696743 -0.24993208
 -0.23250563 -0.31359808 -0.44248135  0.13325916 -0.213121  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.15124788  0.58419804  2.82046782 ...  0.51647583  0.22079196
  0.37893972]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.55929424 -0.65187032 -0.52780645 ...  1.31721779  0.44641014
  0.17466511]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.01350164 1.14004128 1.00233407 0.73768825 0.82676439 0.46102927
 2.07539042 3.08977746 1.33673916 2.71004842 5.80110441 3.51301913
 3.81002335 3.08714813 2.28189865 5.39269221 4.52383028 2.50617537
 2.185139   7.74670377 4.02855058 3.23464816 2.423322   1.26130053
 1.68891274 2.08426005 1.79914045 1.40084828 1.10934814 1.01960006
 0.79434172 0.92281119 3.06050416 4.7616627  4.38127924 2.69088347
 2.12423184 1.79462967 0.69128335 1.23939522 0.28919908 0.19236932
 0.16348165 1.31721779 0.44641014 0.17466511 0.32000909]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.10940073  0.74871394  1.07936784 ...  0.0853494  -0.3330835
 -0.07972046]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.60250837 -0.69851719 -0.56985302 ... -0.14528488  0.06603873
 -0.36790971]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.80125825 -0.8564615  -0.67066712 -0.66448629 -0.66810995 -0.76251296
 -0.64934327 -0.88220888 -0.78418221 -0.82576946 -0.82437575 -0.87759144
 -0.81804949 -0.71627191 -0.61651824 -0.83854317 -0.62008737 -0.57976657
 -0.55551593 -0.63504254 -0.6626987  -0.849602   -0.87644011 -0.80556059
 -0.84242133  0.9772014   0.47370049  1.18561639  0.00525456  0.16451382
 -0.23499774 -0.17743123 -0.32724352 -0.47184452 -0.48561807 -0.21543118
 -0.61611225 -0.76004063 -0.19582827 -0.30847684  0.36111253  0.5704607
  0.08578707 -0.14528488  0.06603873 -0.36790971 -0.10515194]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57478556 -0.53367095 -0.64791926 ... -0.81216559 -0.25535204
 -0.68240463]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5433372  -0.64540812 -0.50861994 ... -0.42237117 -0.76623242
 -0.17426099]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.23245725  0.59263027 -0.23382599 -0.45645064 -0.50324711 -0.67968731
 -0.59202124 -0.89601144 -0.90899901 -0.69033634 -0.8275948  -0.47484969
 -0.35348424 -0.60114346 -0.70431601 -0.8155929  -0.39943677 -0.64831357
 -0.73076142 -0.68051191 -0.7882649  -0.80261178 -0.84705683 -0.79555752
  0.19053756  0.8559377   0.16464618 -0.09818452 -0.35530095 -0.5619424
 -0.54438728 -0.50658419 -0.78123641 -0.54025136 -0.81504531 -0.47645381
 -0.44071868 -0.70845837 -0.8482422  -0.80706981 -0.71815395 -0.68017692
 -0.58839426 -0.42237117 -0.76623242 -0.17426099 -0.62827819]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5314126   0.25300157  0.10319361 ... -0.55868262 -0.68741156
 -0.76004143]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3198738  -0.423429   -0.2846517  ... -0.29023338 -0.50793851
 -0.5217816 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24042309 -0.63902956 -0.7304933  -0.5422848  -0.54142205 -0.66340856
 -0.67625165 -0.56582066 -0.62883352 -0.61569631 -0.40206959 -0.54155277
 -0.43151394 -0.33740969 -0.64680731 -0.47478176 -0.43574922 -0.62484007
 -0.56361152 -0.57648729 -0.74625795 -0.62244792 -0.68539541 -0.71182669
 -0.69904242 -0.69744766 -0.65938243 -0.39129839 -0.533226   -0.52104304
 -0.65925171 -0.72436913 -0.67052618 -0.71612733 -0.7023496  -0.6529903
  0.34538534 -0.34539659  0.42209096  0.51656122  0.33035272 -0.05326034
 -0.31923328 -0.29023338 -0.50793851 -0.5217816  -0.65023214]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.62576817 -0.19995918  1.32780679 ... -0.18073702  0.41114329
  0.05505301]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57782405 -0.67855544 -0.54356241 ... -0.31359808 -0.44248135
  0.13325916]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.18086204  2.43514675  4.8939678   2.95404944  2.30781476  1.9912077
  1.63560888  1.22658631  0.43013827 -0.23735019 -0.18072853  0.03779831
  0.39306017 -0.0185627   0.12479706 -0.02592491 -0.24317385 -0.55042237
  0.03051238 -0.23189529 -0.43590114  0.35861416  0.01498688  0.21936148
  2.01724248  3.45373915  3.1495614   2.26415644  0.97414751  0.65822073
  0.283339    0.05419481 -0.58641966 -0.53749081 -0.60229484 -0.38790051
 -0.36229805 -0.19437215 -0.64794947 -0.32235899  0.06696743 -0.24993208
 -0.23250563 -0.31359808 -0.44248135  0.13325916 -0.213121  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.15124788  0.58419804  2.82046782 ...  0.51647583  0.22079196
  0.37893972]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.55929424 -0.65187032 -0.52780645 ...  1.31721779  0.44641014
  0.17466511]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.01350164 1.14004128 1.00233407 0.73768825 0.82676439 0.46102927
 2.07539042 3.08977746 1.33673916 2.71004842 5.80110441 3.51301913
 3.81002335 3.08714813 2.28189865 5.39269221 4.52383028 2.50617537
 2.185139   7.74670377 4.02855058 3.23464816 2.423322   1.26130053
 1.68891274 2.08426005 1.79914045 1.40084828 1.10934814 1.01960006
 0.79434172 0.92281119 3.06050416 4.7616627  4.38127924 2.69088347
 2.12423184 1.79462967 0.69128335 1.23939522 0.28919908 0.19236932
 0.16348165 1.31721779 0.44641014 0.17466511 0.32000909]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.10940073  0.74871394  1.07936784 ...  0.0853494  -0.3330835
 -0.07972046]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.60250837 -0.69851719 -0.56985302 ... -0.14528488  0.06603873
 -0.36790971]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.80125825 -0.8564615  -0.67066712 -0.66448629 -0.66810995 -0.76251296
 -0.64934327 -0.88220888 -0.78418221 -0.82576946 -0.82437575 -0.87759144
 -0.81804949 -0.71627191 -0.61651824 -0.83854317 -0.62008737 -0.57976657
 -0.55551593 -0.63504254 -0.6626987  -0.849602   -0.87644011 -0.80556059
 -0.84242133  0.9772014   0.47370049  1.18561639  0.00525456  0.16451382
 -0.23499774 -0.17743123 -0.32724352 -0.47184452 -0.48561807 -0.21543118
 -0.61611225 -0.76004063 -0.19582827 -0.30847684  0.36111253  0.5704607
  0.08578707 -0.14528488  0.06603873 -0.36790971 -0.10515194]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57478556 -0.53367095 -0.64791926 ... -0.81216559 -0.25535204
 -0.68240463]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5433372  -0.64540812 -0.50861994 ... -0.42237117 -0.76623242
 -0.17426099]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.23245725  0.59263027 -0.23382599 -0.45645064 -0.50324711 -0.67968731
 -0.59202124 -0.89601144 -0.90899901 -0.69033634 -0.8275948  -0.47484969
 -0.35348424 -0.60114346 -0.70431601 -0.8155929  -0.39943677 -0.64831357
 -0.73076142 -0.68051191 -0.7882649  -0.80261178 -0.84705683 -0.79555752
  0.19053756  0.8559377   0.16464618 -0.09818452 -0.35530095 -0.5619424
 -0.54438728 -0.50658419 -0.78123641 -0.54025136 -0.81504531 -0.47645381
 -0.44071868 -0.70845837 -0.8482422  -0.80706981 -0.71815395 -0.68017692
 -0.58839426 -0.42237117 -0.76623242 -0.17426099 -0.62827819]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5314126   0.25300157  0.10319361 ... -0.55868262 -0.68741156
 -0.76004143]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3198738  -0.423429   -0.2846517  ... -0.29023338 -0.50793851
 -0.5217816 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.65101911 -0.65101911  1.53605321 ... -0.65101911 -0.65101911
 -0.65101911]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24042309 -0.63902956 -0.7304933  -0.5422848  -0.54142205 -0.66340856
 -0.67625165 -0.56582066 -0.62883352 -0.61569631 -0.40206959 -0.54155277
 -0.43151394 -0.33740969 -0.64680731 -0.47478176 -0.43574922 -0.62484007
 -0.56361152 -0.57648729 -0.74625795 -0.62244792 -0.68539541 -0.71182669
 -0.69904242 -0.69744766 -0.65938243 -0.39129839 -0.533226   -0.52104304
 -0.65925171 -0.72436913 -0.67052618 -0.71612733 -0.7023496  -0.6529903
  0.34538534 -0.34539659  0.42209096  0.51656122  0.33035272 -0.05326034
 -0.31923328 -0.29023338 -0.50793851 -0.5217816  -0.65023214]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911
 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911
 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911
 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911

In [16]:
import pandas as pd
r = pd.read_csv(f"{out}/all_baseline_cv_results.csv")
display(r.groupby(["model","feature_set"])[["accuracy","f1","roc_auc","pr_auc","mcc"]].agg(["mean","std"]))

                                              accuracy                  f1  \
                                                  mean       std      mean
model                  feature_set
hist_gradient_boosting market_only            0.517903  0.010443  0.561136
                       market_plus_sentiment  0.509677  0.012244  0.556432
logistic_regression    market_only            0.517742  0.011305  0.557263
                       market_plus_sentiment  0.504032  0.011175  0.537253
random_forest          market_only            0.510161  0.018146  0.541447
                       market_plus_sentiment  0.500806  0.016713  0.535966

                                                         roc_auc            \
                                                   std      mean       std
model                  feature_set
hist_gradient_boosting market_only            0.066018  0.528905  0.021324
                       market_plus_sentiment  0.072050  0.524788  0.020942
logistic_regression    market_only            0.055278  0.527552  0.018759
                       market_plus_sentiment  0.074642  0.521014  0.021206
random_forest          market_only            0.105910  0.528395  0.016939
                       market_plus_sentiment  0.106098  0.523573  0.018266

                                                pr_auc                 mcc  \
                                                  mean       std      mean
model                  feature_set
hist_gradient_boosting market_only            0.526532  0.027271  0.041875
                       market_plus_sentiment  0.525062  0.029253  0.026963
logistic_regression    market_only            0.523750  0.025084  0.036750
                       market_plus_sentiment  0.519968  0.024873  0.010046
random_forest          market_only            0.523730  0.023733  0.029260
                       market_plus_sentiment  0.520017  0.024000  0.004563


                                                   std
model                  feature_set
hist_gradient_boosting market_only            0.019392
                       market_plus_sentiment  0.025752
logistic_regression    market_only            0.022721
                       market_plus_sentiment  0.023059
random_forest          market_only            0.037324
                       market_plus_sentiment  0.035597

## Full deep-learning pipeline
This runs LSTM, GRU, and VAE+Transformer across the walk-forward folds.

In [17]:
!python run_pipeline.py --config config/btc_1h.yaml --stage all

Dataset ready
  rows: 8759
  date: 2025-09-05 00:00:00+00:00 -> 2026-09-04 22:00:00+00:00
  market features: 27
  sentiment features: 10
  dev: 7444 | final purge gap: 1 | final test: 1314
  walk-forward folds: 5

Best baseline by CV: hist_gradient_boosting market_only
Final holdout metrics: {'accuracy': 0.5228310502283106, 'precision': 0.5413223140495868, 'recall': 0.39280359820089955, 'f1': 0.45525629887054736, 'pr_auc': 0.540306640321264, 'mcc': 0.05149297652453508, 'roc_auc': 0.5293906369844444}
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3198738  -0.423429   -0.2846517  ... -0.29023338 -0.50793851
 -0.5217816 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24042309 -0.63902956 -0.7304933  -0.5422848  -0.54142205 -0.66340856
 -0.67625165 -0.56582066 -0.62883352 -0.61569631 -0.40206959 -0.54155277
 -0.43151394 -0.33740969 -0.64680731 -0.47478176 -0.43574922 -0.62484007
 -0.56361152 -0.57648729 -0.74625795 -0.62244792 -0.68539541 -0.71182669
 -0.69904242 -0.69744766 -0.65938243 -0.39129839 -0.533226   -0.52104304
 -0.65925171 -0.72436913 -0.67052618 -0.71612733 -0.7023496  -0.6529903
  0.34538534 -0.34539659  0.42209096  0.51656122  0.33035272 -0.05326034
 -0.31923328 -0.29023338 -0.50793851 -0.5217816  -0.65023214]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.62576817 -0.19995918  1.32780679 ... -0.18073702  0.41114329
  0.05505301]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57782405 -0.67855544 -0.54356241 ... -0.31359808 -0.44248135
  0.13325916]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.18086204  2.43514675  4.8939678   2.95404944  2.30781476  1.9912077
  1.63560888  1.22658631  0.43013827 -0.23735019 -0.18072853  0.03779831
  0.39306017 -0.0185627   0.12479706 -0.02592491 -0.24317385 -0.55042237
  0.03051238 -0.23189529 -0.43590114  0.35861416  0.01498688  0.21936148
  2.01724248  3.45373915  3.1495614   2.26415644  0.97414751  0.65822073
  0.283339    0.05419481 -0.58641966 -0.53749081 -0.60229484 -0.38790051
 -0.36229805 -0.19437215 -0.64794947 -0.32235899  0.06696743 -0.24993208
 -0.23250563 -0.31359808 -0.44248135  0.13325916 -0.213121  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.15124788  0.58419804  2.82046782 ...  0.51647583  0.22079196
  0.37893972]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.55929424 -0.65187032 -0.52780645 ...  1.31721779  0.44641014
  0.17466511]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.01350164 1.14004128 1.00233407 0.73768825 0.82676439 0.46102927
 2.07539042 3.08977746 1.33673916 2.71004842 5.80110441 3.51301913
 3.81002335 3.08714813 2.28189865 5.39269221 4.52383028 2.50617537
 2.185139   7.74670377 4.02855058 3.23464816 2.423322   1.26130053
 1.68891274 2.08426005 1.79914045 1.40084828 1.10934814 1.01960006
 0.79434172 0.92281119 3.06050416 4.7616627  4.38127924 2.69088347
 2.12423184 1.79462967 0.69128335 1.23939522 0.28919908 0.19236932
 0.16348165 1.31721779 0.44641014 0.17466511 0.32000909]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.10940073  0.74871394  1.07936784 ...  0.0853494  -0.3330835
 -0.07972046]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.60250837 -0.69851719 -0.56985302 ... -0.14528488  0.06603873
 -0.36790971]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.80125825 -0.8564615  -0.67066712 -0.66448629 -0.66810995 -0.76251296
 -0.64934327 -0.88220888 -0.78418221 -0.82576946 -0.82437575 -0.87759144
 -0.81804949 -0.71627191 -0.61651824 -0.83854317 -0.62008737 -0.57976657
 -0.55551593 -0.63504254 -0.6626987  -0.849602   -0.87644011 -0.80556059
 -0.84242133  0.9772014   0.47370049  1.18561639  0.00525456  0.16451382
 -0.23499774 -0.17743123 -0.32724352 -0.47184452 -0.48561807 -0.21543118
 -0.61611225 -0.76004063 -0.19582827 -0.30847684  0.36111253  0.5704607
  0.08578707 -0.14528488  0.06603873 -0.36790971 -0.10515194]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57478556 -0.53367095 -0.64791926 ... -0.81216559 -0.25535204
 -0.68240463]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5433372  -0.64540812 -0.50861994 ... -0.42237117 -0.76623242
 -0.17426099]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.23245725  0.59263027 -0.23382599 -0.45645064 -0.50324711 -0.67968731
 -0.59202124 -0.89601144 -0.90899901 -0.69033634 -0.8275948  -0.47484969
 -0.35348424 -0.60114346 -0.70431601 -0.8155929  -0.39943677 -0.64831357
 -0.73076142 -0.68051191 -0.7882649  -0.80261178 -0.84705683 -0.79555752
  0.19053756  0.8559377   0.16464618 -0.09818452 -0.35530095 -0.5619424
 -0.54438728 -0.50658419 -0.78123641 -0.54025136 -0.81504531 -0.47645381
 -0.44071868 -0.70845837 -0.8482422  -0.80706981 -0.71815395 -0.68017692
 -0.58839426 -0.42237117 -0.76623242 -0.17426099 -0.62827819]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5314126   0.25300157  0.10319361 ... -0.55868262 -0.68741156
 -0.76004143]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3198738  -0.423429   -0.2846517  ... -0.29023338 -0.50793851
 -0.5217816 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24042309 -0.63902956 -0.7304933  -0.5422848  -0.54142205 -0.66340856
 -0.67625165 -0.56582066 -0.62883352 -0.61569631 -0.40206959 -0.54155277
 -0.43151394 -0.33740969 -0.64680731 -0.47478176 -0.43574922 -0.62484007
 -0.56361152 -0.57648729 -0.74625795 -0.62244792 -0.68539541 -0.71182669
 -0.69904242 -0.69744766 -0.65938243 -0.39129839 -0.533226   -0.52104304
 -0.65925171 -0.72436913 -0.67052618 -0.71612733 -0.7023496  -0.6529903
  0.34538534 -0.34539659  0.42209096  0.51656122  0.33035272 -0.05326034
 -0.31923328 -0.29023338 -0.50793851 -0.5217816  -0.65023214]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.62576817 -0.19995918  1.32780679 ... -0.18073702  0.41114329
  0.05505301]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57782405 -0.67855544 -0.54356241 ... -0.31359808 -0.44248135
  0.13325916]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.18086204  2.43514675  4.8939678   2.95404944  2.30781476  1.9912077
  1.63560888  1.22658631  0.43013827 -0.23735019 -0.18072853  0.03779831
  0.39306017 -0.0185627   0.12479706 -0.02592491 -0.24317385 -0.55042237
  0.03051238 -0.23189529 -0.43590114  0.35861416  0.01498688  0.21936148
  2.01724248  3.45373915  3.1495614   2.26415644  0.97414751  0.65822073
  0.283339    0.05419481 -0.58641966 -0.53749081 -0.60229484 -0.38790051
 -0.36229805 -0.19437215 -0.64794947 -0.32235899  0.06696743 -0.24993208
 -0.23250563 -0.31359808 -0.44248135  0.13325916 -0.213121  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.15124788  0.58419804  2.82046782 ...  0.51647583  0.22079196
  0.37893972]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.55929424 -0.65187032 -0.52780645 ...  1.31721779  0.44641014
  0.17466511]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.01350164 1.14004128 1.00233407 0.73768825 0.82676439 0.46102927
 2.07539042 3.08977746 1.33673916 2.71004842 5.80110441 3.51301913
 3.81002335 3.08714813 2.28189865 5.39269221 4.52383028 2.50617537
 2.185139   7.74670377 4.02855058 3.23464816 2.423322   1.26130053
 1.68891274 2.08426005 1.79914045 1.40084828 1.10934814 1.01960006
 0.79434172 0.92281119 3.06050416 4.7616627  4.38127924 2.69088347
 2.12423184 1.79462967 0.69128335 1.23939522 0.28919908 0.19236932
 0.16348165 1.31721779 0.44641014 0.17466511 0.32000909]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.10940073  0.74871394  1.07936784 ...  0.0853494  -0.3330835
 -0.07972046]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.60250837 -0.69851719 -0.56985302 ... -0.14528488  0.06603873
 -0.36790971]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.80125825 -0.8564615  -0.67066712 -0.66448629 -0.66810995 -0.76251296
 -0.64934327 -0.88220888 -0.78418221 -0.82576946 -0.82437575 -0.87759144
 -0.81804949 -0.71627191 -0.61651824 -0.83854317 -0.62008737 -0.57976657
 -0.55551593 -0.63504254 -0.6626987  -0.849602   -0.87644011 -0.80556059
 -0.84242133  0.9772014   0.47370049  1.18561639  0.00525456  0.16451382
 -0.23499774 -0.17743123 -0.32724352 -0.47184452 -0.48561807 -0.21543118
 -0.61611225 -0.76004063 -0.19582827 -0.30847684  0.36111253  0.5704607
  0.08578707 -0.14528488  0.06603873 -0.36790971 -0.10515194]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.57478556 -0.53367095 -0.64791926 ... -0.81216559 -0.25535204
 -0.68240463]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5433372  -0.64540812 -0.50861994 ... -0.42237117 -0.76623242
 -0.17426099]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.23245725  0.59263027 -0.23382599 -0.45645064 -0.50324711 -0.67968731
 -0.59202124 -0.89601144 -0.90899901 -0.69033634 -0.8275948  -0.47484969
 -0.35348424 -0.60114346 -0.70431601 -0.8155929  -0.39943677 -0.64831357
 -0.73076142 -0.68051191 -0.7882649  -0.80261178 -0.84705683 -0.79555752
  0.19053756  0.8559377   0.16464618 -0.09818452 -0.35530095 -0.5619424
 -0.54438728 -0.50658419 -0.78123641 -0.54025136 -0.81504531 -0.47645381
 -0.44071868 -0.70845837 -0.8482422  -0.80706981 -0.71815395 -0.68017692
 -0.58839426 -0.42237117 -0.76623242 -0.17426099 -0.62827819]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:501: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.5314126   0.25300157  0.10319361 ... -0.55868262 -0.68741156
 -0.76004143]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ev.loc[:, cols] = scaler.transform(ev[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3198738  -0.423429   -0.2846517  ... -0.29023338 -0.50793851
 -0.5217816 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:499: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.65101911 -0.65101911  1.53605321 ... -0.65101911 -0.65101911
 -0.65101911]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tr.loc[:, cols] = scaler.transform(tr[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24042309 -0.63902956 -0.7304933  -0.5422848  -0.54142205 -0.66340856
 -0.67625165 -0.56582066 -0.62883352 -0.61569631 -0.40206959 -0.54155277
 -0.43151394 -0.33740969 -0.64680731 -0.47478176 -0.43574922 -0.62484007
 -0.56361152 -0.57648729 -0.74625795 -0.62244792 -0.68539541 -0.71182669
 -0.69904242 -0.69744766 -0.65938243 -0.39129839 -0.533226   -0.52104304
 -0.65925171 -0.72436913 -0.67052618 -0.71612733 -0.7023496  -0.6529903
  0.34538534 -0.34539659  0.42209096  0.51656122  0.33035272 -0.05326034
 -0.31923328 -0.29023338 -0.50793851 -0.5217816  -0.65023214]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ctx.loc[:, cols] = scaler.transform(ctx[cols])
/content/drive/MyDrive/BTC reproducible multimodal pipeline/src/pipeline.py:500: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911
 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911
 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911
 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911 -0.65101911

## V4 sentiment-only ablation

Each hourly horizon now compares **market only**, **sentiment only**, and **market + sentiment**. Deep models use max **200 epochs** with validation-loss early stopping (patience 20).

In [ ]:
!python run_horizon_suite.py --stage validate --horizons 1 6 24

In [ ]:
!python run_horizon_suite.py --stage deep --horizons 1 6 24

## Daily paper-style sentiment experiment

This compares next-day **direction**, **return**, and **close-price** prediction using market-only, sentiment-only, and combined inputs. It also includes naive persistence/zero-return baselines.

In [ ]:
!python run_daily_paper_style.py --config config/btc_daily_paper_style.yaml --stage validate

In [ ]:
!python run_daily_paper_style.py --config config/btc_daily_paper_style.yaml --stage all